 
<Face>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            size: root.size
            pos: root.pos


    # Nombre de section de l'interface principal
    rows: 4
    orientation: 'horizontal'

    FloatLayout:
        Button:
            size_hint: .20, .80
            pos_hint:{'x': .05, 'top':.9}
            background_normal: '/home/hunter/Bureau/rouge.png'
            background_down: ''


        Button:
            background_color: (0, 0, 0, 0)
            background_normal: ''
            back_color: 0, 51, 255, 0.2
            border_radius: [18]
            pos_hint:{'x': .8, 'top':.6}
            size_hint: .15, .25
            text: "s'identifier"
            text_color: 0, 51, 255, 0.2
            on_press: print("BUT {}".format(self.pos))
            canvas.before:
                Color:
                    rgba: 0, 0, 0, 0.2
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: self.border_radius



    Label:
        text: "Hunter.apk bientôt prêt\nPlatform Android"
        color: 1,0,1,1

    FloatLayout:
        pos: 10, 50
        Button:
            background_color: (0, 0, 0, 0)
            background_normal: ''
            back_color: 0.12, 30, 0.5
            border_radius: [14]


            pos_hint:{'x': .2, 'top':.8}
            size_hint: .25, .35
            text: 'Se renseigner'
            font_size: 22
            bold: True

            canvas.before:
                Color:
                    rgb: self.back_color
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: self.border_radius

        Button:

            background_color: (0, 0, 0, 0)
            background_normal: ''
            back_color: 0.12, 30, 0.5
            border_radius: [12]

            pos_hint:{'x': .6, 'top':.8}
            size_hint: .25, .35
            text: 'Préscrire'
            font_size: 22
            bold: True

            #on_press: print("BUT {}".format(self.text))

            canvas.before:
                Color:
                    rgb: self.back_color
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: self.border_radius

    BoxLayout:
        Label:
            text: 'A votre service'
            color: 1,0,1,1

